ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    #    hook: "myuniqueid.ngrok.io
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: "https://aa3e-177-93-3-61.ngrok-free.app"

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"